### ISSUE TITLE
How to setup 3 Fab3 

### ISSUE THREAD

**Issue by gnurtcouq** [IBM/loyalty-points-evm-fabric#14]
Hi All,

I tried to add Org3 in Fabric (followed the doc https://hyperledger-fabric.readthedocs.io/en/release-1.4/channel_update_tutorial.html). It seems OK & I can see the new Org3 joined the existing network.

Now I want to create a third Fab3 for the Org3 as in attached file. How can I achieve this?
![3 Fab3 in Blockchain](https://user-images.githubusercontent.com/37733342/56650497-c1ec9100-66b9-11e9-890d-c6e7cef7b538.jpg)

**Comment by horeaporutiu** [comment]
To try and add a 3rd Fab 3, have you tried following these steps https://github.com/IBM/loyalty-points-evm-fabric#4-setup-a-second-fab3 but then change some of the environmental variables for the `FABPROXY_ORG` to be `Org3` and then the `PORT` to be `5002`.

I haven't tried myself, but this is how I would approach this problem. Since this step is not outlined in the README, it is a bit outside the scope of the code pattern. 

This issue will be considered for future code patterns, and I will keep you updated of any documentation showing explicitly how to add additional Fab3.
